name: Process VTT File
on:
  push:
    paths:
      - 'docs/**/*.vtt'
      
jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "A .vtt file was pushed to docs/"
      
  run-conversion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Run conversion script
        run: python convert_vtt_to_md.py
